const date = '2022-09-19 12:23:44';
const globalState = {
  user: {
    email: 'paulo.henrique.hunter@gmail.com',
  },
  wallet: {
    currencies: [
      'USD',
      'CAD',
      'GBP',
      'ARS',
      'BTC',
      'LTC',
      'EUR',
      'JPY',
      'CHF',
      'AUD',
      'CNY',
      'ILS',
      'ETH',
      'XRP',
      'DOGE',
    ],
    expenses: [
      {
        id: 0,
        value: '150',
        description: 'Test expense',
        currency: 'CAD',
        method: 'Cartão de débito',
        tag: 'Alimentação',
        exchangeRates: {
          USD: {
            code: 'USD',
            codein: 'BRL',
            name: 'Dólar Americano/Real Brasileiro',
            high: '5.0897',
            low: '5.047',
            varBid: '0.0141',
            pctChange: '0.28',
            bid: '5.0737',
            ask: '5.0747',
            timestamp: '1661779782',
            create_date: date,
          },
          CAD: {
            code: 'CAD',
            codein: 'BRL',
            name: 'Dólar Canadense/Real Brasileiro',
            high: '3.9044',
            low: '3.8703',
            varBid: '0.0155',
            pctChange: '0.4',
            bid: '3.8957',
            ask: '3.8977',
            timestamp: '1661779783',
            create_date: date,
          },
          GBP: {
            code: 'GBP',
            codein: 'BRL',
            name: 'Libra Esterlina/Real Brasileiro',
            high: '5.9563',
            low: '5.8951',
            varBid: '-0.0009',
            pctChange: '-0.02',
            bid: '5.941',
            ask: '5.945',
            timestamp: '1661779783',
            create_date: date,
          },
          ARS: {
            code: 'ARS',
            codein: 'BRL',
            name: 'Peso Argentino/Real Brasileiro',
            high: '0.0369',
            low: '0.0365',
            varBid: '0',
            pctChange: '0',
            bid: '0.0367',
            ask: '0.0367',
            timestamp: '1661779782',
            create_date: date,
          },
          BTC: {
            code: 'BTC',
            codein: 'BRL',
            name: 'Bitcoin/Real Brasileiro',
            high: '102.958',
            low: '100.011',
            varBid: '56',
            pctChange: '0.06',
            bid: '101.735',
            ask: '101.915',
            timestamp: '1661778999',
            create_date: date,
          },
          LTC: {
            code: 'LTC',
            codein: 'BRL',
            name: 'Litecoin/Real Brasileiro',
            high: '286.54',
            low: '270',
            varBid: '9.64',
            pctChange: '3.51',
            bid: '282.86',
            ask: '284.11',
            timestamp: '1661778979',
            create_date: date,
          },
          EUR: {
            code: 'EUR',
            codein: 'BRL',
            name: 'Euro/Real Brasileiro',
            high: '5.0883',
            low: '5.0173',
            varBid: '0.0361',
            pctChange: '0.72',
            bid: '5.0757',
            ask: '5.0768',
            timestamp: '1661779784',
            create_date: date,
          },
          JPY: {
            code: 'JPY',
            codein: 'BRL',
            name: 'Iene Japonês/Real Brasileiro',
            high: '0.03676',
            low: '0.03644',
            varBid: '-0.0001',
            pctChange: '-0.27',
            bid: '0.03662',
            ask: '0.03668',
            timestamp: '1661779785',
            create_date: date,
          },
          CHF: {
            code: 'CHF',
            codein: 'BRL',
            name: 'Franco Suíço/Real Brasileiro',
            high: '5.2599',
            low: '5.213',
            varBid: '0.0127',
            pctChange: '0.24',
            bid: '5.2463',
            ask: '5.2475',
            timestamp: '1661779781',
            create_date: date,
          },
          AUD: {
            code: 'AUD',
            codein: 'BRL',
            name: 'Dólar Australiano/Real Brasileiro',
            high: '3.504',
            low: '3.4621',
            varBid: '0.0151',
            pctChange: '0.43',
            bid: '3.5009',
            ask: '3.5018',
            timestamp: '1661779784',
            create_date: date,
          },
          CNY: {
            code: 'CNY',
            codein: 'BRL',
            name: 'Yuan Chinês/Real Brasileiro',
            high: '0.7365',
            low: '0.7306',
            varBid: '-0.0035',
            pctChange: '-0.48',
            bid: '0.7342',
            ask: '0.7344',
            timestamp: '1661779742',
            create_date: date,
          },
          ILS: {
            code: 'ILS',
            codein: 'BRL',
            name: 'Novo Shekel Israelense/Real Brasileiro',
            high: '1.5394',
            low: '1.519',
            varBid: '-0.0124',
            pctChange: '-0.81',
            bid: '1.5297',
            ask: '1.53',
            timestamp: '1661779743',
            create_date: date,
          },
          ETH: {
            code: 'ETH',
            codein: 'BRL',
            name: 'Ethereum/Real Brasileiro',
            high: '7.9',
            low: '7.3',
            varBid: '34.68',
            pctChange: '0.46',
            bid: '7.5678',
            ask: '7.57924',
            timestamp: '1661778998',
            create_date: date,
          },
          XRP: {
            code: 'XRP',
            codein: 'BRL',
            name: 'XRP/Real Brasileiro',
            high: '1.73',
            low: '1.63',
            varBid: '-0.05',
            pctChange: '-2.89',
            bid: '1.66',
            ask: '1.67',
            timestamp: '1661778999',
            create_date: date,
          },
          DOGE: {
            code: 'DOGE',
            codein: 'BRL',
            name: 'Dogecoin/Real Brasileiro',
            high: '0.326271',
            low: '0.309915',
            varBid: '-0.002383',
            pctChange: '-0.74',
            bid: '0.320066',
            ask: '0.320066',
            timestamp: '1661779784',
            create_date: date,
          },
        },
      },
    ],

    idEdit: 0,
    onEdit: false,
  },
};

export default globalState;
